In [1]:
print("OK")

OK

mmongodb+srv://entarfin:<db_password>@cluster0.y9ggd0v.mongodb.net/?appName=Cluster0

In [2]:
import pandas as pd

In [ ]:
%pwd

'd:\\Bappy\\Live Sessions\\Inception\\End-to-End-Machine-Learning-Project-Implementation\\notebooks'

In [3]:
df = pd.read_csv("Visadataset.csv")
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [4]:
df.shape

(25480, 12)

In [5]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [6]:
data = df.to_dict(orient='records')
data

[{'case_id': 'EZYV01',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 14513,
  'yr_of_estab': 2007,
  'region_of_employment': 'West',
  'prevailing_wage': 592.2029,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV02',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2412,
  'yr_of_estab': 2002,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 83425.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV03',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 44444,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 122996.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV04',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 98,
  'yr_of_estab': 1897,
  'region_of_employment': 'West',
  'prevailing_wage': 83434.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV05',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1082,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 149907.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV06',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2339,
  'yr_of_estab': 2012,
  'region_of_employment': 'South',
  'prevailing_wage': 78252.14,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV07',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 4985,
  'yr_of_estab': 1994,
  'region_of_employment': 'South',
  'prevailing_wage': 53635.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV08',
  'continent': 'North America',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3035,
  'yr_of_estab': 1924,
  'region_of_employment': 'West',
  'prevailing_wage': 418.2298,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV09',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 4810,
  'yr_of_estab': 2012,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 74362.19,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV10',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2251,
  'yr_of_estab': 1995,
  'region_of_employment': 'South',
  'prevailing_wage': 67514.76,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV11',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2465,
  'yr_of_estab': 2004,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 83588.56,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV12',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4069,
  'yr_of_estab': 2005,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 70813.09,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV13',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 123876,
  'yr_of_estab': 1963,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 28663.05,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV14',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1652,
  'yr_of_estab': 2007,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 107196.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV15',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 15756,
  'yr_of_estab': 2006,
  'region_of_employment': 'South',
  'prevailing_wage': 220081.73,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV16',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4897,
  'yr_of_estab': 1987,
  'region_of_employment': 'West',
  'prevailing_wage': 74108.02,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV17',
  'continent': 'Europe',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 76638,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 3706.79,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV18',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2747,
  'yr_of_estab': 2001,
  'region_of_employment': 'West',
  'prevailing_wage': 16132.61,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV19',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4743,
  'yr_of_estab': 2004,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 150441.13,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV20',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 843,
  'yr_of_estab': 1972,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 79948.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV21',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 880,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 71128.98,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV22',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1706,
  'yr_of_estab': 2013,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 137694.98,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV23',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2878,
  'yr_of_estab': 1968,
  'region_of_employment': 'West',
  'prevailing_wage': 45642.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV24',
  'continent': 'North America',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1517,
  'yr_of_estab': 1884,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 90108.38,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV25',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 241,
  'yr_of_estab': 1981,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 71286.04,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV26',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1100,
  'yr_of_estab': 1997,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 99489.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV27',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 756,
  'yr_of_estab': 1995,
  'region_of_employment': 'South',
  'prevailing_wage': 86332.95,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV28',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 2889,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 103029.33,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV29',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 18,
  'yr_of_estab': 2004,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 40925.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV30',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 758,
  'yr_of_estab': 2009,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 189190.48,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV31',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1408,
  'yr_of_estab': 1998,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 79594.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV32',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 995,
  'yr_of_estab': 1880,
  'region_of_employment': 'South',
  'prevailing_wage': 135866.13,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV33',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2415,
  'yr_of_estab': 1963,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 72077.57,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV34',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2395,
  'yr_of_estab': 2000,
  'region_of_employment': 'South',
  'prevailing_wage': 81921.18,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV35',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1809,
  'yr_of_estab': 2010,
  'region_of_employment': 'South',
  'prevailing_wage': 225569.73,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV36',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 5512,
  'yr_of_estab': 2001,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 92421.92,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV37',
  'continent': 'Europe',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2520,
  'yr_of_estab': 1981,
  'region_of_employment': 'West',
  'prevailing_wage': 2490.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV38',
  'continent': 'Europe',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 44,
  'yr_of_estab': 1965,
  'region_of_employment': 'South',
  'prevailing_wage': 110817.26,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV39',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 2206,
  'yr_of_estab': 1909,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 50960.01,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV40',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 3729,
  'yr_of_estab': 2007,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 125336.9,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV41',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3723,
  'yr_of_estab': 2011,
  'region_of_employment': 'West',
  'prevailing_wage': 39633.32,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV42',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1209,
  'yr_of_estab': 1989,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 156326.33,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV43',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 19770,
  'yr_of_estab': 2005,
  'region_of_employment': 'West',
  'prevailing_wage': 43630.58,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV44',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2582,
  'yr_of_estab': 1989,
  'region_of_employment': 'South',
  'prevailing_wage': 54614.42,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV45',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 5407,
  'yr_of_estab': 1998,
  'region_of_employment': 'West',
  'prevailing_wage': 28989.87,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV46',
  'continent': 'Europe',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 2092,
  'yr_of_estab': 1998,
  'region_of_employment': 'South',
  'prevailing_wage': 22924.91,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV47',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2623,
  'yr_of_estab': 2008,
  'region_of_employment': 'South',
  'prevailing_wage': 61567.75,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV48',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 226,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 156251.17,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV49',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2405,
  'yr_of_estab': 1933,
  'region_of_employment': 'South',
  'prevailing_wage': 86022.02,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV50',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 2171,
  'yr_of_estab': 1960,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 49565.37,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV51',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 746,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 66191.41,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV52',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3129,
  'yr_of_estab': 2003,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 95623.2,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV53',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1647,
  'yr_of_estab': 1998,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 115014.05,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV54',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2438,
  'yr_of_estab': 1976,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 35018.04,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV55',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 11733,
  'yr_of_estab': 1995,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 230.8072,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV56',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2368,
  'yr_of_estab': 1998,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 113799.64,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV57',
  'continent': 'Europe',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 779,
  'yr_of_estab': 1994,
  'region_of_employment': 'West',
  'prevailing_wage': 85854.09,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',

In [7]:
DB_NAME = "US_VISA"
COLLECTION_NAME = "visa_data"
CONNECTION_URL = "mongodb+srv://entbappy:entbappy@cluster0.3lowor9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

In [9]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 21.1 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 26.5 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0

In [10]:
import pymongo

client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

# rec = collection.insert_many(data)

# get data

In [11]:
records = collection.find()
records

In [12]:
for i, j in enumerate(records):
    print(f"{i} : {j}")

Streaming output truncated to the last 5000 lines.
20480 : {'_id': ObjectId('68a73e8fec8f9c8f169d5701'), 'case_id': 'EZYV20422', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1615, 'yr_of_estab': 1965, 'region_of_employment': 'Northeast', 'prevailing_wage': 824.7957, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
20481 : {'_id': ObjectId('68a73e8fec8f9c8f169d5702'), 'case_id': 'EZYV20423', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5402, 'yr_of_estab': 2007, 'region_of_employment': 'Northeast', 'prevailing_wage': 80102.8, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20482 : {'_id': ObjectId('68a73e8fec8f9c8f169d570a'), 'case_id': 'EZYV20431', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 37986, 'yr_of_estab': 1987, 'region_of_employment': 'Midwest', 'prevailing_wage': 5018.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20483 : {'_id': ObjectId('68a73e8fec8f9c8f169d570d'), 'case_id': 'EZYV20434', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 833, 'yr_of_estab': 2009, 'region_of_employment': 'South', 'prevailing_wage': 148435.04, 'unit_of_wage': 'Week', 'full_time_position': 'Y', 'case_status': 'Certified'}
20484 : {'_id': ObjectId('68a73e8fec8f9c8f169d5711'), 'case_id': 'EZYV20438', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3817, 'yr_of_estab': 1996, 'region_of_employment': 'Northeast', 'prevailing_wage': 104342.21, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20485 : {'_id': ObjectId('68a73e8fec8f9c8f169d5714'), 'case_id': 'EZYV20441', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1382, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 132034.19, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20486 : {'_id': ObjectId('68a73e8fec8f9c8f169d5717'), 'case_id': 'EZYV20444', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2005, 'yr_of_estab': 2010, 'region_of_employment': 'West', 'prevailing_wage': 80040.61, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20487 : {'_id': ObjectId('68a73e8fec8f9c8f169d5722'), 'case_id': 'EZYV20455', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1409, 'yr_of_estab': 1943, 'region_of_employment': 'West', 'prevailing_wage': 140806.51, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
20488 : {'_id': ObjectId('68a73e8fec8f9c8f169d5728'), 'case_id': 'EZYV20461', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1299, 'yr_of_estab': 2004, 'region_of_employment': 'South', 'prevailing_wage': 109289.68, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20489 : {'_id': ObjectId('68a73e8fec8f9c8f169d572c'), 'case_id': 'EZYV20465', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1154, 'yr_of_estab': 1977, 'region_of_employment': 'South', 'prevailing_wage': 52.0516, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
20490 : {'_id': ObjectId('68a73e8fec8f9c8f169d5733'), 'case_id': 'EZYV20472', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1887, 'yr_of_estab': 1969, 'region_of_employment': 'South', 'prevailing_wage': 283.9495, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
20491 : {'_id': ObjectId('68a73e8fec8f9c8f169d5735'), 'case_id': 'EZYV20474', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3105, 'yr_of_estab': 1888, 'region_of_employment': 'Northeast', 'prevailing_wage': 103373.34, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20492 : {'_id': ObjectId('68a73e8fec8f9c8f169d5739'), 'case_id': 'EZYV20478', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 22009, 'yr_of_estab': 2008, 'region_of_employment': 'Northeast', 'prevailing_wage': 126351.57, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20493 : {'_id': ObjectId('68a73e8fec8f9c8f169d573b'), 'case_id': 'EZYV20480', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 905, 'yr_of_estab': 2013, 'region_of_employment': 'South', 'prevailing_wage': 114755.59, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20494 : {'_id': ObjectId('68a73e8fec8f9c8f169d573c'), 'case_id': 'EZYV20481', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2184, 'yr_of_estab': 2012, 'region_of_employment': 'West', 'prevailing_wage': 11323.59, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20495 : {'_id': ObjectId('68a73e8fec8f9c8f169d573d'), 'case_id': 'EZYV20482', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 452, 'yr_of_estab': 1997, 'region_of_employment': 'West', 'prevailing_wage': 153531.71, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20496 : {'_id': ObjectId('68a73e8fec8f9c8f169d5745'), 'case_id': 'EZYV20490', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2734, 'yr_of_estab': 1974, 'region_of_employment': 'Northeast', 'prevailing_wage': 444.8704, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
20497 : {'_id': ObjectId('68a73e8fec8f9c8f169d5746'), 'case_id': 'EZYV20491', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 848, 'yr_of_estab': 1989, 'region_of_employment': 'Northeast', 'prevailing_wage': 2450.22, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20498 : {'_id': ObjectId('68a73e8fec8f9c8f169d5748'), 'case_id': 'EZYV20493', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4658, 'yr_of_estab': 1968, 'region_of_employment': 'Northeast', 'prevailing_wage': 101356.75, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20499 : {'_id': ObjectId('68a73e8fec8f9c8f169d574c'), 'case_id': 'EZYV20497', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4253, 'yr_of_estab': 2010, 'region_of_employment': 'Northeast', 'prevailing_wage': 173819.06, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20500 : {'_id': ObjectId('68a73e8fec8f9c8f169d5752'), 'case_id': 'EZYV20503', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3758, 'yr_of_estab': 2010, 'region_of_employment': 'West', 'prevailing_wage': 74839.73, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20501 : {'_id': ObjectId('68a73e8fec8f9c8f169d5757'), 'case_id': 'EZYV20508', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1766, 'yr_of_estab': 1807, 'region_of_employment': 'Northeast', 'prevailing_wage': 42536.72, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20502 : {'_id': ObjectId('68a73e8fec8f9c8f169d575a'), 'case_id': 'EZYV20511', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4540, 'yr_of_estab': 1985, 'region_of_employment': 'West', 'prevailing_wage': 51269.58, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20503 : {'_id': ObjectId('68a73e8fec8f9c8f169d575c'), 'case_id': 'EZYV20513', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3261, 'yr_of_estab': 2006, 'region_of_employment': 'Northeast', 'prevailing_wage': 104060.84, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20504 : {'_id': ObjectId('68a73e8fec8f9c8f169d575d'), 'case_id': 'EZYV20514', 'continent': 'North America', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2177, 'yr_of_estab': 1993, 'region_of_employment': 'West', 'prevailing_wage': 10327.68, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20505 : {'_id': ObjectId('68a73e8fec8f9c8f169d5761'), 'case_id': 'EZYV20518', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1527, 'yr_of_estab': 1993, 'region_of_employment': 'South', 'prevailing_wage': 69071.97, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20506 : {'_id': ObjectId('68a73e8fec8f9c8f169d5763'), 'case_id': 'EZYV20520', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 4602, 'yr_of_estab': 1948, 'region_of_employment': 'West', 'prevailing_wage': 91223.72, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20507 : {'_id': ObjectId('68a73e8fec8f9c8f169d5765'), 'case_id': 'EZYV20522', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2318, 'yr_of_estab': 1928, 'region_of_employment': 'South', 'prevailing_wage': 129283.7, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20508 : {'_id': ObjectId('68a73e8fec8f9c8f169d576b'), 'case_id': 'EZYV20528', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 30724, 'yr_of_estab': 2012, 'region_of_employment': 'Northeast', 'prevailing_wage': 17278.62, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20509 : {'_id': ObjectId('68a73e8fec8f9c8f169d576c'), 'case_id': 'EZYV20529', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3422, 'yr_of_estab': 1995, 'region_of_employment': 'Northeast', 'prevailing_wage': 395.9807, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
20510 : {'_id': ObjectId('68a73e8fec8f9c8f169d5774'), 'case_id': 'EZYV20537', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 1109, 'yr_of_estab': 1992, 'region_of_employment': 'South', 'prevailing_wage': 65616.87, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20511 : {'_id': ObjectId('68a73e8fec8f9c8f169d5777'), 'case_id': 'EZYV20540', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 128666, 'yr_of_estab': 2011, 'region_of_employment': 'Northeast', 'prevailing_wage': 113208.82, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20512 : {'_id': ObjectId('68a73e8fec8f9c8f169d577b'), 'case_id': 'EZYV20544', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2987, 'yr_of_estab': 2003, 'region_of_employment': 'Midwest', 'prevailing_wage': 109697.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20513 : {'_id': ObjectId('68a73e8fec8f9c8f169d5787'), 'case_id': 'EZYV20556', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 531, 'yr_of_estab': 1839, 'region_of_employment': 'Northeast', 'prevailing_wage': 89782.38, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20514 : {'_id': ObjectId('68a73e8fec8f9c8f169d578d'), 'case_id': 'EZYV20562', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3688, 'yr_of_estab': 2014, 'region_of_employment': 'Midwest', 'prevailing_wage': 131390.99, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
20515 : {'_id': ObjectId('68a73e8fec8f9c8f169d5791'), 'case_id': 'EZYV20566', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1922, 'yr_of_estab': 2012, 'region_of_employment': 'South', 'prevailing_wage': 84268.36, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20516 : {'_id': ObjectId('68a73e8fec8f9c8f169d5798'), 'case_id': 'EZYV20573', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 50, 'yr_of_estab': 1998, 'region_of_employment': 'South', 'prevailing_wage': 63485.6, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20517 : {'_id': ObjectId('68a73e8fec8f9c8f169d579a'), 'case_id': 'EZYV20575', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 1082, 'yr_of_estab': 1994, 'region_of_employment': 'Northeast', 'prevailing_wage': 137411.29, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20518 : {'_id': ObjectId('68a73e8fec8f9c8f169d57a4'), 'case_id': 'EZYV20585', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4317, 'yr_of_estab': 2010, 'region_of_employment': 'Northeast', 'prevailing_wage': 49559.33, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20519 : {'_id': ObjectId('68a73e8fec8f9c8f169d57aa'), 'case_id': 'EZYV20591', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4045, 'yr_of_estab': 1991, 'region_of_employment': 'West', 'prevailing_wage': 46302.56, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20520 : {'_id': ObjectId('68a73e8fec8f9c8f169d57ac'), 'case_id': 'EZYV20593', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1586, 'yr_of_estab': 2003, 'region_of_employment': 'West', 'prevailing_wage': 5400.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20521 : {'_id': ObjectId('68a73e8fec8f9c8f169d57ad'), 'case_id': 'EZYV20594', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 50854, 'yr_of_estab': 2006, 'region_of_employment': 'South', 'prevailing_wage': 56956.33, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20522 : {'_id': ObjectId('68a73e8fec8f9c8f169d57ae'), 'case_id': 'EZYV20595', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3873, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 238778.59, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
20523 : {'_id': ObjectId('68a73e8fec8f9c8f169d57b2'), 'case_id': 'EZYV20599', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1172, 'yr_of_estab': 2011, 'region_of_employment': 'Northeast', 'prevailing_wage': 163204.24, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20524 : {'_id': ObjectId('68a73e8fec8f9c8f169d57b5'), 'case_id': 'EZYV20602', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 3922, 'yr_of_estab': 2001, 'region_of_employment': 'West', 'prevailing_wage': 615.32, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
20525 : {'_id': ObjectId('68a73e8fec8f9c8f169d57b9'), 'case_id': 'EZYV20606', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2422, 'yr_of_estab': 1974, 'region_of_employment': 'Midwest', 'prevailing_wage': 98892.66, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20526 : {'_id': ObjectId('68a73e8fec8f9c8f169d57bf'), 'case_id': 'EZYV20612', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 619, 'yr_of_estab': 1974, 'region_of_employment': 'Midwest', 'prevailing_wage': 63622.48, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
20527 : {'_id': ObjectId('68a73e8fec8f9c8f169d57c1'), 'case_id': 'EZYV20614', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 24850, 'yr_of_estab': 2005, 'region_of_employment': 'West', 'prevailing_wage': 77302.08, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20528 : {'_id': ObjectId('68a73e8fec8f9c8f169d57c9'), 'case_id': 'EZYV20622', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 521, 'yr_of_estab': 1994, 'region_of_employment': 'West', 'prevailing_wage': 57188.54, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20529 : {'_id': ObjectId('68a73e8fec8f9c8f169d57cd'), 'case_id': 'EZYV20626', 'continent': 'North America', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 87661, 'yr_of_estab': 2000, 'region_of_employment': 'West', 'prevailing_wage': 844.7739, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
20530 : {'_id': ObjectId('68a73e8fec8f9c8f169d57d0'), 'case_id': 'EZYV20629', 'continent': 'Oceania', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2666, 'yr_of_estab': 2013, 'region_of_employment': 'West', 'prevailing_wage': 60233.11, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

In [13]:
df = pd.DataFrame(list(collection.find()))

In [14]:
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,68a73e8fec8f9c8f169d0741,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.14,Year,Y,Certified
1,68a73e8fec8f9c8f169d0742,EZYV07,Asia,Bachelor's,N,N,4985,1994,South,53635.39,Year,Y,Certified
2,68a73e8fec8f9c8f169d0759,EZYV30,Asia,Bachelor's,Y,N,758,2009,Northeast,189190.48,Year,Y,Certified
3,68a73e8fec8f9c8f169d075a,EZYV31,Asia,Master's,Y,N,1408,1998,Midwest,79594.12,Year,N,Certified
4,68a73e8fec8f9c8f169d075b,EZYV32,Asia,Doctorate,Y,N,995,1880,South,135866.13,Year,N,Certified

In [15]:
if "_id" in df.columns.to_list():
    df.drop(columns=["_id"], inplace=True)

In [16]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.14,Year,Y,Certified
1,EZYV07,Asia,Bachelor's,N,N,4985,1994,South,53635.39,Year,Y,Certified
2,EZYV30,Asia,Bachelor's,Y,N,758,2009,Northeast,189190.48,Year,Y,Certified
3,EZYV31,Asia,Master's,Y,N,1408,1998,Midwest,79594.12,Year,N,Certified
4,EZYV32,Asia,Doctorate,Y,N,995,1880,South,135866.13,Year,N,Certified